
services:
  db:
    image: postgres:16
    container_name: lapince_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lapince
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: ./back
      dockerfile: Dockerfile.api
    restart: always
    depends_on:
    - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules

    container_name: lapince-api

volumes:
  pgdata:
